require(twitteR)
searchTerm='#SOPA'
rdmTweets <- searchTwitter(searchTerm, n=500)

tw.df=twListToDF(rdmTweets)

require(plyr)
tw.dfx=ddply(tw.df, .var = "screenName", .fun = function(x) {return(subset(x, created %in% min(created),select=c(screenName,created)))})
tw.dfxa=arrange(tw.dfx,-desc(created))
tw.df$screenName=factor(tw.df$screenName, levels = tw.dfxa$screenName)
require(ggplot2)
pdf("/Users/sciruela/Documents/twitterHashtagsAnalysis/graph1.pdf")
ggplot(tw.df)+geom_point(aes(x=created,y=screenName))
dev.off()
library(stringr)
trim <- function (x) sub('@','',x)
tw.df$rt=sapply(tw.df$text,function(tweet) trim(str_match(tweet,"^RT (@[[:alnum:]_]*)")[2]))
tw.df$rtt=sapply(tw.df$rt,function(rt) if (is.na(rt)) 'T' else 'RT')
pdf("/Users/sciruela/Documents/twitterHashtagsAnalysis/graph2.pdf")
ggplot(tw.df)+geom_point(aes(x=created,y=screenName,col=rtt))
dev.off()
tw.df$rtof=sapply(tw.df$text,function(tweet) trim(str_match(tweet,"^RT (@[[:alnum:]_]*)")[2]))
pdf("/Users/sciruela/Documents/twitterHashtagsAnalysis/graph3.pdf")
ggplot(subset(tw.df,subset=(!is.na(rtof))))+geom_point(aes(x=created,y=rtof))
dev.off()

require(gdata)
tw.df.rt=drop.levels(subset(tw.df,subset=(!is.na(rtof))))
tw.df.rta=arrange(ddply(tw.df.rt, .var = "screenName", .fun = function(x) {return(subset(x, created %in% min(created),select=c(screenName,created)))}),-desc(created))
tw.df.rt$screenName=factor(tw.df.rt$screenName, levels = tw.df.rta$screenName)
pdf("/Users/sciruela/Documents/twitterHashtagsAnalysis/graph4.pdf")
ggplot(subset(tw.df.rt,subset=(!is.na(rtof))))+geom_point(aes(x=screenName,y=rtof))+opts(axis.text.x=theme_text(angle=-90,size=6)) + xlab(NULL)
dev.off()

